name: CI

on:
  # push:
    # branches: [main]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build release
        run: cargo build --target x86_64-pc-windows-msvc
