name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
